name: Mirror to INRAE Forge
on: [push]
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-filter-repo
        run: pip install git-filter-repo

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.INRAE_FORGE_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan forge.inrae.fr >> ~/.ssh/known_hosts

      - name: Remove unwanted files from Git history
        run: |
          git filter-repo --path sample/*/input/*/*.csv --path sample/*/output/**/*.csv --path sample/*/output/**/*.txt --invert-paths --force

      - name: Push to INRAE Forge
        run: |
          git remote add inrae ${{ secrets.INRAE_FORGE_REPO }}
          git push --mirror inrae